version: '3.9'

services:

  finazapp_image:
    image: finazapp-api
    container_name: finazapp-api-container
    ports:
      - "8862:8862"
    networks:
      - spring-network
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: postgres_database
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: edding350
        POSTGRES_DB: PruebaHost
    ports:
      - "5433:5432"
    networks:
      - spring-network
    volumes:
      - postgres-volume:/var/lib/postgresql/data
networks:
  spring-network:
volumes:
  postgres-volume: